# 应用的配置文件
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/springboot-study?character=utf-8&useSSL=false

mybatis:
  configuration:
    # 设置map-underscore-to-camel-case属性为true来开启驼峰功能
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

